### ISSUE TITLE
lab2/task_8.py

### ISSUE THREAD

**Issue by AndreevP** [python-practice-b02-927/davit.zohrabyan#14]
В задании просили использовать функцию, которая строит правильный многоугольник (например функция от радиуса описанной окружности и числа вершин). Исправьте.

**Comment by davzohr** [comment]
я использовал

**Comment by davzohr** [comment]
я использовал фолмулу для радиуса

**Comment by davzohr** [comment]
Я же вроде написал

**Comment by davzohr** [comment]
сделано

**Comment by AndreevP** [comment]
Аргументы функции лучше передавать в саму функцию (f(r, n) например), а название у функции должны быть каким-то адекватным, а не просто f. Доделайте с учетом рекомендаций

**Comment by davzohr** [comment]
сделал
