### ISSUE TITLE
Рисуйте траектории lab3_3/three_bodies_problem.py

### ISSUE THREAD

**Issue by PeganovAnton** [python-practice-b02-927/davit.zohrabyan#17]
Рисуйте траектории тел. Это можно сделать, проставляя точки в месте нахождения тела каждые `n`  шагов. Число `n` подбирается так, чтобы траектория хорошо просматривалась, но чтобы вычисления не тормозили из-за большого числа объектов.

**Comment by davzohr** [comment]
уже рисуется
